import React from 'react';
import { X } from 'lucide-react';
import { soundManager } from '../services/soundService';

interface HowToPlayModalProps {
  onClose: () => void;
}

export const HowToPlayModal: React.FC<HowToPlayModalProps> = ({ onClose }) => {
  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div
        className="glass-panel"
        onClick={(e) => e.stopPropagation()}
        style={{
          width: '100%',
          maxWidth: '680px',
          maxHeight: '85vh',
          overflowY: 'auto',
          padding: '32px',
          position: 'relative',
          background: 'rgba(15, 23, 42, 0.95)',
          border: '1px solid var(--border-bright)',
        }}
      >
        {/* Close button */}
        <button
          onClick={() => {
            soundManager.playClick();
            onClose();
          }}
          style={{
            position: 'absolute',
            top: '20px',
            right: '20px',
            background: 'transparent',
            border: 'none',
            color: 'var(--text-muted)',
            cursor: 'pointer',
            padding: '4px',
          }}
        >
          <X size={22} />
        </button>

        {/* Title */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '20px' }}>
          <div style={{
            width: '42px',
            height: '42px',
            borderRadius: '12px',
            background: 'linear-gradient(135deg, #06b6d4 0%, #8b5cf6 100%)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: '22px',
          }}>
            📜
          </div>
          <div>
            <h2 style={{ fontSize: '24px', color: '#fff', margin: 0 }}>How to Play</h2>
            <p style={{ color: 'var(--text-secondary)', fontSize: '13px' }}>
              Official Rulebook & Tactical Protocol
            </p>
          </div>
        </div>

        {/* Steps List */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', textAlign: 'left' }}>
          {/* Rule 1 */}
          <div style={{
            background: 'rgba(255, 255, 255, 0.03)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: '16px',
            display: 'flex',
            gap: '14px',
          }}>
            <div style={{ fontSize: '24px' }}>🛡️</div>
            <div>
              <h4 style={{ color: 'var(--cyan-accent)', marginBottom: '4px' }}>1. Roles & Secret Words</h4>
              <p style={{ color: 'var(--text-secondary)', fontSize: '14px', lineHeight: '1.5' }}>
                At the start of the game, a random <strong>Secret Word</strong> and <strong>Category</strong> are generated by Gemini AI.
                <strong> Crewmates</strong> receive both the Secret Word & Category.
                <strong> The Imposter</strong> only receives the Category and a single cryptic hint!
              </p>
            </div>
          </div>

          {/* Rule 2 */}
          <div style={{
            background: 'rgba(255, 255, 255, 0.03)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: '16px',
            display: 'flex',
            gap: '14px',
          }}>
            <div style={{ fontSize: '24px' }}>💬</div>
            <div>
              <h4 style={{ color: '#a78bfa', marginBottom: '4px' }}>2. Clue Sharing Phase</h4>
              <p style={{ color: 'var(--text-secondary)', fontSize: '14px', lineHeight: '1.5' }}>
                Players take turns giving a short, 1-sentence clue about the word.
                <strong> Crewmates</strong> must hint they know the word without making it so obvious that the Imposter figures it out.
                <strong> Imposters</strong> must bluff and craft believable clues using their single hint!
              </p>
            </div>
          </div>

          {/* Rule 3 */}
          <div style={{
            background: 'rgba(255, 255, 255, 0.03)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: '16px',
            display: 'flex',
            gap: '14px',
          }}>
            <div style={{ fontSize: '24px' }}>🚨</div>
            <div>
              <h4 style={{ color: '#f59e0b', marginBottom: '4px' }}>3. Emergency Voting</h4>
              <p style={{ color: 'var(--text-secondary)', fontSize: '14px', lineHeight: '1.5' }}>
                After the discussion rounds, players vote for the person they suspect is the Imposter.
                Inspect previous transmitted clues to spot weak or overly generic answers.
              </p>
            </div>
          </div>

          {/* Rule 4 */}
          <div style={{
            background: 'rgba(255, 255, 255, 0.03)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)',
            padding: '16px',
            display: 'flex',
            gap: '14px',
          }}>
            <div style={{ fontSize: '24px' }}>🏆</div>
            <div>
              <h4 style={{ color: '#10b981', marginBottom: '4px' }}>4. Win Conditions</h4>
              <p style={{ color: 'var(--text-secondary)', fontSize: '14px', lineHeight: '1.5' }}>
                • <strong>Crew Wins</strong> if the majority votes out the true Imposter (and the Imposter fails the clutch guess).<br />
                • <strong>Imposter Wins</strong> if an innocent crewmate is ejected, if votes tie, or if the Imposter correctly guesses the secret word!
              </p>
            </div>
          </div>
        </div>

        <button
          type="button"
          onClick={() => {
            soundManager.playClick();
            onClose();
          }}
          className="btn-primary"
          style={{ width: '100%', marginTop: '24px', padding: '14px' }}
        >
          Understood • Ready to Play
        </button>
      </div>
    </div>
  );
};
